<?php

namespace Database\Seeders;

use App\Models\Course;
use App\Models\CoursePart;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CourseCatalogSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $courses = [
            [
                'slug' => 'auto-detailing',
                'title_ar' => 'العناية المتقدمة بالسيارات وحماية النانو سيراميك',
                'title_en' => 'Advanced Auto Detailing & Nano-Ceramic Protection',
                'description_ar' => 'دورة مهنية تطبيقية لإتقان تلميع وتفصيل هياكل السيارات وتطبيق طبقات الحماية النانو سيراميك 9H ومعالجة دوائر الغسيل والخدوش في أجواء الصيف العراقية الحارة.',
                'description_en' => 'Hands-on vocational training to master paint correction, swirl removal, and 9H nano-ceramic coating tailored for harsh desert and summer climates.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1607860108855-64acf2078ed9?auto=format&fit=crop&q=80&w=1200',
                'bundle_price_cents' => 1000,
                'bundle_promotional_tickets' => 15,
                'display_price_label' => '13,000 IQD',
                'is_active' => true,
                'parts' => [
                    [
                        'part_number' => 1,
                        'title_ar' => 'أساسيات الغسيل الكيميائي وإزالة الشوائب والـ Clay Bar',
                        'title_en' => 'Chemical Decontamination Fundamentals & Clay Bar Treatment',
                        'syllabus_ar' => 'معادلة الحموضة، استخدام رغوة الثلج، إزالة برادة الحديد وقضيب الطين لحماية الطلاء الأصلي.',
                        'syllabus_en' => 'PH neutrality, snow foam pre-wash, iron fallout removal, and clay bar treatment.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 45,
                    ],
                    [
                        'part_number' => 2,
                        'title_ar' => 'تقييم الطلاء واستخدام مقياس السمك الرقمي بالميكرون',
                        'title_en' => 'Paint Assessment & Digital Gauge Micron Metering',
                        'syllabus_ar' => 'قياس الميكرون، تشخيص طبقة الكليير كوت، وتحديد الخدوش القابلة للمعالجة دون إتلاف الصبغ.',
                        'syllabus_en' => 'Micron measurement, clear coat health inspection, and identifying corrective scratch limits.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 50,
                    ],
                    [
                        'part_number' => 3,
                        'title_ar' => 'معالجة الخدوش والتلميع بمكائن الروتاري والديوال أكشن',
                        'title_en' => 'Rotary & Dual-Action Multi-Stage Paint Correction',
                        'syllabus_ar' => 'العمل بأجهزة الروتاري والديوال أكشن، واختيار الوسائد والمعاجين المناسبة لحرارة الصيف العراقية.',
                        'syllabus_en' => 'Rotary and dual-action polishers, pad and compound matching for Iraqi summer climate.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 60,
                    ],
                    [
                        'part_number' => 4,
                        'title_ar' => 'تجهيز السطح الكحولي وتطبيق طبقات النانو سيراميك 9H',
                        'title_en' => 'IPA Prep & 9H Nano-Ceramic Coating Application',
                        'syllabus_ar' => 'مسح الإيزوبروبيل IPA، فرد طبقات السيراميك 9H، ومراقبة الوميض ومسح الزوائد بدقة وتثبيتها بالأشعة.',
                        'syllabus_en' => 'IPA wipe-down, 9H ceramic coating leveling, flash-time detection, and infrared curing.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 55,
                    ],
                    [
                        'part_number' => 5,
                        'title_ar' => 'العناية بالفرش الداخلي والجلود والمعالجة بالبخار الحار',
                        'title_en' => 'Interior Upholstery Deep Extraction & Steam Detailing',
                        'syllabus_ar' => 'تنظيف الجلد الطبيعي، ترطيب الأسطح، غسيل المقاعد بالحقن والاستخلاص والتعقيم الحراري.',
                        'syllabus_en' => 'Leather rejuvenation, deep extraction washing, and pressurized steam sanitization.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 40,
                    ],
                    [
                        'part_number' => 6,
                        'title_ar' => 'تسويق خدمات التلميع وإدارة ورشة ديتيلينغ في العراق',
                        'title_en' => 'Detailing Workshop Costing, Management & Local Marketing',
                        'syllabus_ar' => 'حساب تكلفة المواد، تسعير الباقات للزبائن العراقيين، وتصوير فيديوهات التحول لإنستغرام وتيك توك.',
                        'syllabus_en' => 'Material cost accounting, package pricing in IQD, and social media reels marketing.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 45,
                    ],
                ],
            ],
            [
                'slug' => 'phone-repair',
                'title_ar' => 'صيانة الهواتف الذكية واللحام الدقيق للميكروإلكترونيات',
                'title_en' => 'Smartphones Hardware Repair & Microsoldering',
                'description_ar' => 'تشخيص أعطال البورد وحقن الفولتية، تتبع مسارات VDD_MAIN عبر المخططات، شبلنة رقاقات BGA واستبدال دوائر الشحن والشاشات باحترافية.',
                'description_en' => 'Master logic board diagnostics, voltage injection, schematic tracing via ZXW, BGA IC reballing, and screen refurbishment.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1597740985671-2a8a3b80532e?auto=format&fit=crop&q=80&w=1200',
                'bundle_price_cents' => 1000,
                'bundle_promotional_tickets' => 15,
                'display_price_label' => '13,000 IQD',
                'is_active' => true,
                'parts' => [
                    [
                        'part_number' => 1,
                        'title_ar' => 'قراءة المخططات الإلكترونية وتتبع خطوط التغذية الرئيسية VDD/VCC',
                        'title_en' => 'Schematic Analysis & Primary Power Rail Tracing',
                        'syllabus_ar' => 'استخدام برامج ZXW و XinZhiZao لفحص خطوط التغذية واكتشاف انقطاع المسارات.',
                        'syllabus_en' => 'Using ZXW and XinZhiZao for schematic analysis and primary rail fault isolation.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 45,
                    ],
                    [
                        'part_number' => 2,
                        'title_ar' => 'استخدام الأفوميتر والكاميرا الحرارية لرصد الشورت الصريح والنسبي',
                        'title_en' => 'Multimeter & Thermal Camera Diagnostic Workflows',
                        'syllabus_ar' => 'قياس الممانعة على وضع الدايود، واستخدام دخان الرزينة والكاميرا الحرارية لتحديد المكون التالف.',
                        'syllabus_en' => 'Diode mode impedance testing, rosin vapor method, and thermal camera heat mapping.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 50,
                    ],
                    [
                        'part_number' => 3,
                        'title_ar' => 'تقنيات اللحام بالهوت إير وتنظيف الشبلنة لرقاقات BGA',
                        'title_en' => 'Hot Air Rework & Precision BGA IC Reballing',
                        'syllabus_ar' => 'ضبط حرارة الهوت إير، رفع الأيسيات المحمية بالإيبوكسي، وشبلنة كرات القصدير بدقة 0.2mm.',
                        'syllabus_en' => 'Underfill glue removal, BGA stencil reballing with 0.2mm solder paste.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 65,
                    ],
                    [
                        'part_number' => 4,
                        'title_ar' => 'إصلاح مسارات الشحن ودائرة الإضاءة في هواتف الآيفون والأندرويد',
                        'title_en' => 'Charging Port & Backlight Circuit Diagnostics',
                        'syllabus_ar' => 'تبديل آيسي الترايستار/هايدرا، فحص ملفات الإضاءة ودايود البوست وفلاتر الشاشة.',
                        'syllabus_en' => 'Tristar/Hydra IC replacement, backlight boost coil, and display filter testing.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 55,
                    ],
                    [
                        'part_number' => 5,
                        'title_ar' => 'استبدال شاشات OLED ونقل بيانات تروتون وفك الفلاتات',
                        'title_en' => 'Curved OLED Screen Separation & TrueTone Serialization',
                        'syllabus_ar' => 'فك الشاشات المنحنية بجهاز التسخين، ونقل السيريال عبر المبرمجة لتفعيل تروتون والبطارية.',
                        'syllabus_en' => 'Curved OLED screen disassembly, EEPROM programmer serialization for TrueTone.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 40,
                    ],
                    [
                        'part_number' => 6,
                        'title_ar' => 'تجهيز معمل الصيانة وتسعير قطع الغيار في السوق العراقي',
                        'title_en' => 'Repair Lab Setup & Spare Parts Sourcing in Local Markets',
                        'syllabus_ar' => 'أفضل مصادر قطع الغيار في بغداد (شارع الربيعي/باب الشرقي)، وتسعير أجور اليد وضمان التصليح.',
                        'syllabus_en' => 'Sourcing original spare parts in Baghdad market, labor pricing, and repair warranties.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 45,
                    ],
                ],
            ],
            [
                'slug' => 'solar-installation',
                'title_ar' => 'تصميم وتركيب منظومات الطاقة الشمسية الهجينة والمنفصلة عن الشبكة وبرمجة الإنفرترات وبنوك بطاريات الليثيوم',
                'title_en' => 'Design, Installation & Troubleshooting of Hybrid & Off-Grid Solar PV Systems, Inverters and Lithium Battery Banks',
                'description_ar' => 'دليل هندسي وميداني متكامل لتصميم منظومات الطاقة الشمسية للمنازل والمزارع والمعامل في العراق، حساب أحمال الذروة، برمجة محولات الديركت الهايبرد، وتوصيل بطاريات LiFePO4 بأمان تام.',
                'description_en' => 'A complete end-to-end engineering and field manual for residential and commercial solar systems: sizing peak kilowatt-hour loads, programming MPPT hybrid inverters, and safely wiring LiFePO4 battery banks.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&q=80&w=1200',
                'bundle_price_cents' => 1500,
                'bundle_promotional_tickets' => 25,
                'display_price_label' => '20,000 IQD',
                'is_active' => true,
                'parts' => [
                    [
                        'part_number' => 1,
                        'title_ar' => 'أساسيات الإشعاع الشمسي وحساب أحمال الاستهلاك المنزلي في العراق',
                        'title_en' => 'Solar Irradiance Basics & Household Load Calculation in Iraq',
                        'syllabus_ar' => 'حساب استهلاك الكيلوواط ساعي للأجهزة المنزلية، أحمال تشغيل مكيفات السبلت، وتقدير ساعات السطوع الشمسي الفعلي في الصيف والشتاء.',
                        'syllabus_en' => 'Calculating kWh consumption for home appliances, AC starting surges, and measuring peak sun hours in summer vs winter.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 50,
                    ],
                    [
                        'part_number' => 2,
                        'title_ar' => 'اختيار الألواح الشمسية (Monocrystalline vs Bifacial) وحساب الفولتية Voc و Isc',
                        'title_en' => 'Solar Panel Selection (Mono vs Bifacial) & String Sizing (Voc/Isc)',
                        'syllabus_ar' => 'فهم كفاءة خلايا N-Type و P-Type، حساب أقصى تيار وفولتية الدائرة المفتوحة مع مراعاة درجات الحرارة المرتفعة.',
                        'syllabus_en' => 'N-Type vs P-Type cell efficiency, open-circuit voltage (Voc) temperature coefficients, and short-circuit current calculations.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 60,
                    ],
                    [
                        'part_number' => 3,
                        'title_ar' => 'قواعد تثبيت الهياكل المعدنية وزوايا الميل ومقاومة الرياح والعواصف الترابية',
                        'title_en' => 'Mounting Racks, Tilt Angle Optimization & Dust Storm Mitigation',
                        'syllabus_ar' => 'تحديد زاوية الميل المثالية (28°-32° في العراق)، تثبيت الهياكل المجلفنة على الأسطح الخرسانية، وحلول تنظيف الغبار.',
                        'syllabus_en' => 'Optimal tilt angle (28°-32° for Iraq), galvanized steel anchoring on concrete roofs, and dust mitigation strategies.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 45,
                    ],
                    [
                        'part_number' => 4,
                        'title_ar' => 'برمجة إنفرترات الهايبرد والديركت وإعدادات شحن MPPT',
                        'title_en' => 'Hybrid Inverter Programming & MPPT Charge Tuning',
                        'syllabus_ar' => 'ضبط أولويات التغذية (Solar / Battery / Utility)، برمجة إنفرترات Deye و Growatt، ومعايرة أقصى تيار شحن.',
                        'syllabus_en' => 'Configuring priority modes (SUB / SBU / SOL), setting up Deye & Growatt inverters, and calibrating MPPT charge current.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 70,
                    ],
                    [
                        'part_number' => 5,
                        'title_ar' => 'تجميع وربط بنوك بطاريات الليثيوم LiFePO4 وبرمجة جهاز BMS',
                        'title_en' => 'Lithium Battery Bank Wiring & BMS Configuration',
                        'syllabus_ar' => 'توصيل خلايا فوسفات الحديد الليثيوم على التوالي والتوازي (16S 48V)، برمجة بروتوكولات CAN/RS485 للاتصال بالإنفرتر.',
                        'syllabus_en' => 'Assembling 16S 48V LiFePO4 battery packs, configuring Smart BMS, and establishing CAN/RS485 communication with inverters.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 65,
                    ],
                    [
                        'part_number' => 6,
                        'title_ar' => 'قواطع الحماية DC والمانعات الصواعق والتأريض الوقائي',
                        'title_en' => 'DC Breakers, Surge Protection Devices & Protective Grounding',
                        'syllabus_ar' => 'حساب سعة قواطع الـ DC، تركيب مانعات الصواعق SPD، ودفن أوتاد التأريض لقياس مقاومة أرضي أقل من 5 أوم.',
                        'syllabus_en' => 'Sizing DC circuit breakers, installing Type II surge protectors, and driving copper ground rods for <5 ohm earth resistance.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 55,
                    ],
                    [
                        'part_number' => 7,
                        'title_ar' => 'ربط منظومة الطاقة الشمسية مع سحب المولد الأهلي والشبكة الوطنية (ATS)',
                        'title_en' => 'Interfacing Solar with Local Generators & National Grid via ATS',
                        'syllabus_ar' => 'برمجة محول التحويل التلقائي (ATS)، عزل خط المولد لضمان عدم ارتداد التيار، وحماية الإنفرتر من ذبذبة مولدات الديزل.',
                        'syllabus_en' => 'Automatic Transfer Switch (ATS) interlocking, backfeed isolation, and protecting inverters from generator frequency instability.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 60,
                    ],
                    [
                        'part_number' => 8,
                        'title_ar' => 'الصيانة الدورية، كشف الخلايا الساخنة (Hotspots) بالكاميرا الحرارية، وعقود الصيانة',
                        'title_en' => 'Thermal Hotspot Inspection, Preventative Maintenance & Service Contracts',
                        'syllabus_ar' => 'الفحص الدوري بالأشعة تحت الحمراء لكشف الدايودات المحترقة، غسيل الألواح بمياه منزوعة الأملاح، وتسعير عقود الصيانة السنوية.',
                        'syllabus_en' => 'Infrared drone/thermal hotspot audits, demineralized water washing routines, and crafting annual preventative service SLAs.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 50,
                    ],
                ],
            ],
            [
                'slug' => 'freelance-design',
                'title_ar' => 'تصميم الهويات البصرية والواجهات والعمل الحر في العراق',
                'title_en' => 'Brand Identity, UI Design & Local Freelancing',
                'description_ar' => 'مسار عملي لبناء العلامات التجارية وتصميم الواجهات بفيكما، استقطاب العملاء المحليين على منصات العمل الحر، وتلقي المدفوعات عبر زين كاش وبطاقات الدفع الإلكتروني.',
                'description_en' => 'Build cohesive brand identities, craft modern UI systems in Figma, pitch local clients, and handle digital payment workflows in Iraq.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1626785774573-4b799315345d?auto=format&fit=crop&q=80&w=1200',
                'bundle_price_cents' => 1000,
                'bundle_promotional_tickets' => 15,
                'display_price_label' => '13,000 IQD',
                'is_active' => true,
                'parts' => [
                    [
                        'part_number' => 1,
                        'title_ar' => 'أساسيات بناء الهوية البصرية ونظرية الألوان والخطوط العربية',
                        'title_en' => 'Visual Identity Fundamentals & Arabic Typography',
                        'syllabus_ar' => 'اختيار الخطوط الطباعية المتناسقة، معاني الألوان للمستهلك العراقي، ودليل استخدام الشعار.',
                        'syllabus_en' => 'Arabic font pairing, cultural color psychology, and comprehensive brand guidelines.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 45,
                    ],
                    [
                        'part_number' => 2,
                        'title_ar' => 'تصميم واجهات المستخدم وتجربة الاستخدام ببرنامج فيجما',
                        'title_en' => 'Figma UI/UX Components, Auto-Layout & RTL Patterns',
                        'syllabus_ar' => 'بناء شبكات التصميم، الأوتولايوت، المكونات التفاعلية، وتصميم واجهات عربية RTL متقنة.',
                        'syllabus_en' => 'Grid systems, Auto-layout, variants, and Arabic RTL interface design patterns.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 60,
                    ],
                    [
                        'part_number' => 3,
                        'title_ar' => 'تصميم إعلانات السوشيال ميديا للمتاجر والمطاعم العراقية',
                        'title_en' => 'High-Converting Social Media Creatives for Local Brands',
                        'syllabus_ar' => 'مقاسات المنشورات والستوري، دمج الصور وتوزيع النصوص الجاذبة للفت انتباه المشتري.',
                        'syllabus_en' => 'Feed & Story ad composition, photo manipulation, and high-converting CTA text.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 50,
                    ],
                    [
                        'part_number' => 4,
                        'title_ar' => 'بناء البورتفوليو الاحترافي على بيهانس ولينكد إن',
                        'title_en' => 'Behance Case Studies & Client Pitch Decks',
                        'syllabus_ar' => 'عرض دراسة الحالة (Case Study) وكتابة التحدي والحلول لإقناع الشركات بتوظيفك.',
                        'syllabus_en' => 'Presenting design case studies, outlining problems & solutions to win client pitches.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 40,
                    ],
                    [
                        'part_number' => 5,
                        'title_ar' => 'استراتيجيات التسعير والتفاوض وكتابة العقود القانونية',
                        'title_en' => 'Value-Based Pricing, Client Negotiation & Scope Contracts',
                        'syllabus_ar' => 'التسعير القائم على القيمة مقابل السعر الثابت، صياغة عقود حفظ الحقوق واستلام الدفعة المقدمة.',
                        'syllabus_en' => 'Value-based pricing vs flat rate, deposit clauses, and freelance service agreements.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 45,
                    ],
                    [
                        'part_number' => 6,
                        'title_ar' => 'إدارة التحويلات المالية عبر زين كاش والماستر كارد المحلية',
                        'title_en' => 'Managing Digital Payments via ZainCash Merchant & Local Gateways',
                        'syllabus_ar' => 'استلام دفعات العمل الحر في العراق، ربط الحسابات المصرفية، وتجنب مشاكل المعاملات المالية.',
                        'syllabus_en' => 'Collecting freelance fees via Zain Cash merchant wallets, Qi card, and bank transfers.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 35,
                    ],
                ],
            ],
            [
                'slug' => 'hvac-refrigeration',
                'title_ar' => 'صيانة مكيفات الإنفرتر ومبردات الهواء وتشخيص ضواغط التبريد',
                'title_en' => 'Inverter Air Conditioning Diagnostics & Compressor Servicing',
                'description_ar' => 'تشخيص كروت التحكم الإلكترونية (PCB)، شحن وضبط غازات R410A و R32 بميزان رقمي، كشف التسريبات النيتروجينية، وصيانة ضواغط السبلت لمقاومة درجات الحرارة فوق 50 مئوية.',
                'description_en' => 'Diagnose inverter PCB circuits, recharge R410A and R32 refrigerants with digital scales, locate micro-leaks using nitrogen pressure testing, and service rotary compressors.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&q=80&w=1200',
                'bundle_price_cents' => 1000,
                'bundle_promotional_tickets' => 15,
                'display_price_label' => '13,000 IQD',
                'is_active' => true,
                'parts' => [
                    [
                        'part_number' => 1,
                        'title_ar' => 'الدورة الميكانيكية لغازات التبريد وفروق الضغط ودرجة الغليان',
                        'title_en' => 'Refrigeration Cycle & Saturation Pressure Principles',
                        'syllabus_ar' => 'شرح دورة التبريد الانضغاطية، وظيفة المبخر والمكثف وصمام التمدد، وجداول الضغط والحرارة (PT Chart).',
                        'syllabus_en' => 'Compressive cooling cycle, evaporator & condenser physics, thermal expansion valves, and PT charts.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 45,
                    ],
                    [
                        'part_number' => 2,
                        'title_ar' => 'كشف التسريب الدقيق باستخدام ضغط غاز النيتروجين الجاف',
                        'title_en' => 'Micro-Leak Detection Using Pressurized Dry Nitrogen',
                        'syllabus_ar' => 'عزل الوحدة الداخلية والخارجية، ضغط المنظومة بـ 450 PSI غاز نيتروجين، واستخدام رغوة المايكرو للكشف.',
                        'syllabus_en' => 'Isolating indoor/outdoor units, pressurizing to 450 PSI with dry nitrogen, and bubble-testing braze joints.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 50,
                    ],
                    [
                        'part_number' => 3,
                        'title_ar' => 'تفريغ الهواء بمضخة الفاكيوم وشحن غاز R410A/R32 بالميزان الإلكتروني',
                        'title_en' => 'Vacuum Dehydration & Precision Weigh-in Refrigerant Charging',
                        'syllabus_ar' => 'سحب الرطوبة وصولاً إلى 500 ميكرون، قلب أسطوانة R410A للشحن السائل، وحساب الطول الإضافي للأنابيب.',
                        'syllabus_en' => 'Deep vacuum down to 500 microns, liquid-state charging with digital scale, and pipe length compensation grams.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 55,
                    ],
                    [
                        'part_number' => 4,
                        'title_ar' => 'فحص أكواد الأعطال (Error Codes) وتتبع كارت الإنفرتر والموتور DC',
                        'title_en' => 'Troubleshooting Inverter PCB Boards & DC Fan Motors',
                        'syllabus_ar' => 'تشخيص أكواد الخطأ لمكيفات جنرال وميديا وتوسوت، فحص موديول IPM بالملتيميتر، واختبار حساسات الثيرمستور.',
                        'syllabus_en' => 'Decoding error codes on Midea & General units, testing IPM power modules with diode tests, and sensor checks.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 65,
                    ],
                    [
                        'part_number' => 5,
                        'title_ar' => 'فك واستبدال ضاغط السبلت واللحام بأكسي-أسيتيلين مع تدفق النيتروجين',
                        'title_en' => 'Rotary Compressor Replacement & Nitrogen-Purge Brazing',
                        'syllabus_ar' => 'تفريغ الزيت المحترق، اللحام بأسياخ الفضة تحت تدفق خفيف من النيتروجين لمنع الأكسدة الكربونية داخل المواسير.',
                        'syllabus_en' => 'Acid flushing contaminated systems, silver alloy brazing under nitrogen purge to prevent carbon scale formation.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 60,
                    ],
                ],
            ],
            [
                'slug' => 'cctv-smart-security',
                'title_ar' => 'تمديد كاميرات المراقبة وأنظمة الإنذار',
                'title_en' => 'IP CCTV & Smart Security Systems',
                'description_ar' => 'ربط وبرمجة كاميرات المراقبة الشبكية (IP & PoE)، ضبط أجهزة التسجيل NVR، وتفعيل المشاهدة عن بعد عبر الهاتف.',
                'description_en' => 'Install and configure IP & PoE cameras, setup NVR storage, and enable remote cloud monitoring on mobile devices.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&q=80&w=1200',
                'bundle_price_cents' => 800,
                'bundle_promotional_tickets' => 10,
                'display_price_label' => '10,000 IQD',
                'is_active' => true,
                'parts' => [
                    [
                        'part_number' => 1,
                        'title_ar' => 'كبس كابلات Cat6 وتوصيل سويتشات PoE وتوزيع الكاميرات',
                        'title_en' => 'Cat6 Crimping, PoE Switch Wiring & Camera Placement',
                        'syllabus_ar' => 'معايير T568B في كبس الفيش RJ45، حساب مسافات الفولتية لسويتشات PoE، واختيار العدسات البؤرية (2.8mm vs 4mm).',
                        'syllabus_en' => 'T568B crimping standard, PoE wattage budget calculation, and focal length selection for perimeter coverage.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 40,
                    ],
                    [
                        'part_number' => 2,
                        'title_ar' => 'تهيئة عناوين IP الثابتة وإعداد مسجل الفيديو الشبكي (NVR)',
                        'title_en' => 'Static IP Allocation & NVR Recording Configuration',
                        'syllabus_ar' => 'تخصيص العناوين عبر أدوات SADP/ConfigTool، تهيئة الهارد ديسك بنظام التخزين H.265+ لتوفير مساحة التسجيل.',
                        'syllabus_en' => 'Assigning static subnets via SADP/ConfigTool, formatting surveillance HDDs, and optimizing H.265+ compression.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 45,
                    ],
                    [
                        'part_number' => 3,
                        'title_ar' => 'ضبط حساسات الحركة الذكية والتعرف على الوجوه ولوحات السيارات',
                        'title_en' => 'AI Motion Detection, Facial Recognition & Vehicle LPR Setup',
                        'syllabus_ar' => 'تفعيل خوارزميات AcuSense لتفادي الإنذارات الكاذبة من الحيوانات والرياح، ورسم خطوط العبور الافتراضية (Tripwire).',
                        'syllabus_en' => 'Configuring smart AcuSense analytics, virtual tripwire intrusion detection, and vehicle license plate recognition.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 50,
                    ],
                    [
                        'part_number' => 4,
                        'title_ar' => 'فتح المنافذ وتفعيل خدمة السحابة P2P للمشاهدة الحية عبر الهاتف',
                        'title_en' => 'P2P Cloud Setup & Mobile Live Monitoring Across Subnets',
                        'syllabus_ar' => 'ربط أجهزة هيكفيجن وداهوا بتطبيقات Hik-Connect و DMSS، مشاركة الصلاحيات مع صاحب العمل وحماية كلمات السر.',
                        'syllabus_en' => 'Pairing Hik-Connect & DMSS cloud services via QR code, managing multi-tier user privileges, and cyber hardening.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 35,
                    ],
                ],
            ],
            [
                'slug' => 'barber-styling',
                'title_ar' => 'فنون الحلاقة الرجالية الحديثة والتدريج وتأسيس الصالون',
                'title_en' => "Modern Men's Haircutting, Fade Techniques & Barbershop Management",
                'description_ar' => 'تعلم تقنيات تدريج الشعر الاحترافي (Skin Fade)، نحت اللحية بالشفرة الكلاسيكية، بروتوكولات التعقيم الصحي، وإدارة تكاليف وأرباح صالون الحلاقة العصري.',
                'description_en' => 'Master precision skin fades, classic straight-razor beard sculpting, strict sanitization protocols, and financial management for modern barbershops.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&q=80&w=1200',
                'bundle_price_cents' => 1000,
                'bundle_promotional_tickets' => 15,
                'display_price_label' => '13,000 IQD',
                'is_active' => true,
                'parts' => [
                    [
                        'part_number' => 1,
                        'title_ar' => 'تشريح الرأس ونظرية التدريج وتجهيز الماكينات والمقصات',
                        'title_en' => 'Cranial Geometry, Machine Tuning & Clipper Guard Rules',
                        'syllabus_ar' => 'ضبط شفرات الماكينة على الزيرو غاب (Zero Gap)، معايرة أمشاط التدريج، وقواعد توزيع الظلال على الجمجمة.',
                        'syllabus_en' => 'Zero-gapping clippers, guard identification from #0.5 to #4, and bone structure shading geometry.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 45,
                    ],
                    [
                        'part_number' => 2,
                        'title_ar' => 'تقنيات التدريج العالي والمتوسط والمنخفض (Low, Mid & High Fade)',
                        'title_en' => 'Low, Mid & High Skin Fade Blending Techniques',
                        'syllabus_ar' => 'رسم خط البداية (Guideline)، محو الخط الفاصل بحركة الـ Flick-out، واستخدام ماكينة الفويل لتنعيم الصفر.',
                        'syllabus_en' => 'Establishing baseline guidelines, flick-out lever fading motions, and foil shaver finishing for pristine skin fades.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 60,
                    ],
                    [
                        'part_number' => 3,
                        'title_ar' => 'القص بالمقص فوق المشط ونحت الطبقات العلوية (Scissor Over Comb)',
                        'title_en' => 'Scissor-Over-Comb Texturizing & Layering',
                        'syllabus_ar' => 'التحكم في زوايا سحب الخصلات، قص الغرة والتاج، واستخدام مقص التخفيف (Thinning Shears) لإعطاء كثافة طبيعية.',
                        'syllabus_en' => 'Sectioning patterns, scissor-over-comb blending between sides and top, and texturizing with thinning shears.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 50,
                    ],
                    [
                        'part_number' => 4,
                        'title_ar' => 'تحديد اللحية بالموس الكلاسيكي وتطبيق المناشف الحارة ومساج الوجه',
                        'title_en' => 'Straight Razor Beard Sculpting, Hot Towel & Face Care',
                        'syllabus_ar' => 'شد الجلد بزاوية 30 درجة للموس، رسم خطوط الخد والرقبة بدقة، وتطبيق الزيوت الطبيعية والمناشف البخارية.',
                        'syllabus_en' => '30-degree straight razor blade angle, cheekbone line symmetry, hot towel pore opening, and beard oil nourishment.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 45,
                    ],
                    [
                        'part_number' => 5,
                        'title_ar' => 'معايير النظافة والتعقيم بمحاليل بارباسايد والأشعة فوق البنفسجية',
                        'title_en' => 'Barbicide Sanitization, UV Sterilization & Hygiene Standards',
                        'syllabus_ar' => 'منع انتقال العدوى الفطرية والجلدية، تعقيم الشفرات بين كل زبون، واستخدام أطواق العنق الورقية الطبية.',
                        'syllabus_en' => 'Bloodborne pathogen safety, hospital-grade Barbicide immersion, UV cabinet tool sterilization, and hygienic neck strips.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 35,
                    ],
                    [
                        'part_number' => 6,
                        'title_ar' => 'دراسة جدوى فتح صالون حلاقة عصري وتسعير الخدمات وتسويق الإنستغرام',
                        'title_en' => 'Modern Barbershop Feasibility, Pricing & Social Marketing',
                        'syllabus_ar' => 'تكلفة كراسي الحلاقة والديكور، نظام النسبة المئوية للحلاقين، وتصوير فيديوهات التحول (Before/After) لجلب الزبائن.',
                        'syllabus_en' => 'Capex budget for chairs and lighting, barber commission split models, and high-impact Instagram before/after reels.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 45,
                    ],
                ],
            ],
            [
                'slug' => 'specialty-coffee-barista',
                'title_ar' => 'فن الباريستا واستخلاص القهوة المختصة',
                'title_en' => 'Specialty Coffee Barista & Espresso Science',
                'description_ar' => 'معايرة الطواحين، استخلاص الإسبريسو المتوازن، وتبخير الحليب للرسم (Latte Art).',
                'description_en' => 'Dialing-in espresso grinders, extraction ratio science, and microfoam latte art.',
                'cover_image_url' => 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&q=80&w=1200',
                'bundle_price_cents' => 800,
                'bundle_promotional_tickets' => 10,
                'display_price_label' => '10,000 IQD',
                'is_active' => true,
                'parts' => [
                    [
                        'part_number' => 1,
                        'title_ar' => 'كيمياء حبوب القهوة، درجات التحميص ومناطق الزراعة',
                        'title_en' => 'Coffee Bean Processing, Roasting Profiles & Origins',
                        'syllabus_ar' => 'الفرق بين الأرابيكا والروبوستا، المعالجة المجففة والمغسولة، وتأثير ارتفاع مزارع إثيوبيا وكولومبيا على الإيحاءات.',
                        'syllabus_en' => 'Arabica vs Robusta, natural vs washed processing, elevation influence on acidity, and tasting note development.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 40,
                    ],
                    [
                        'part_number' => 2,
                        'title_ar' => 'معايرة طاحونة الإسبريسو وتحديد نسبة الاستخلاص (Brew Ratio 1:2)',
                        'title_en' => 'Grinder Dialing-in, Dosing & 1:2 Brew Ratio Calibration',
                        'syllabus_ar' => 'ضبط ميكرون الطحن، توزيع البن بأداة WDT، الكبس المتوازن بضغط 15 كجم، وتوقيت استخلاص 36 جرام في 28 ثانية.',
                        'syllabus_en' => 'Stepless burr adjustments, WDT puck preparation, 15kg level tamping, and hitting 36g yield in 28 seconds.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 45,
                    ],
                    [
                        'part_number' => 3,
                        'title_ar' => 'هيدروديناميكا تبخير الحليب ورسم القلوب والورود (Latte Art)',
                        'title_en' => 'Milk Steaming Hydrodynamics & Latte Art Mechanics',
                        'syllabus_ar' => 'صنع رغوة المايكروفوم الحريرية بحرارة 60-65 مئوية، تقنية الصب البطيء للرسم (Heart, Rosetta, Tulip).',
                        'syllabus_en' => 'Creating silky microfoam at 60-65°C, vortex steam wand angle, and flow control for poured hearts and rosettas.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 50,
                    ],
                    [
                        'part_number' => 4,
                        'title_ar' => 'سرعة خدمة الزبائن (Workflow)، تنظيف ماكينة الإسبريسو وإدارة هدر البن',
                        'title_en' => 'Cafe Workflow Ergonomics, Backflushing & Bean Waste Control',
                        'syllabus_ar' => 'ترتيب محطة الباريستا، تنظيف رأس المجموعة بالباك فلاش ومسحوق كافيزا، وحساب تكلفة الكوب ونسبة الهدر اليومي.',
                        'syllabus_en' => 'Ergonomic station setup, chemical backflushing with Cafiza, steam wand decalcification, and daily yield cost logs.',
                        'part_price_cents' => 200,
                        'part_promotional_tickets' => 1,
                        'display_price_label' => '2,000 IQD',
                        'resource_types' => ['video', 'pdf'],
                        'duration_minutes' => 35,
                    ],
                ],
            ],
        ];

        foreach ($courses as $cData) {
            $parts = $cData['parts'];
            unset($cData['parts']);

            $course = Course::firstOrCreate(
                ['slug' => $cData['slug']],
                $cData
            );

            foreach ($parts as $pData) {
                if (!isset($pData['is_free'])) {
                    $pData['is_free'] = ((int) $pData['part_number'] === 1);
                }
                CoursePart::firstOrCreate(
                    [
                        'course_id' => $course->id,
                        'part_number' => $pData['part_number'],
                    ],
                    $pData
                );
            }
        }
    }
}
